export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCRSS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const FIELD_CHANGED = 'FIELD_CHANGED';
export const EMPLOYEE_FORM_RESET = 'EMPLOYEE_FORM_RESET';
export const EMPLOYEES_FETCH_SUCCESS = 'EMPLOYEES_FETCH_SUCCESS';